// Mocks generated by Mockito 5.4.6 from annotations
// in eventshot_mobile/test/unit/offline_upload_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:eventshot_mobile/features/attendee/data/repositories/attendee_repository.dart'
    as _i2;
import 'package:eventshot_mobile/features/events/domain/entities/event.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AttendeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendeeRepository extends _i1.Mock
    implements _i2.AttendeeRepository {
  MockAttendeeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Event?> validateJoinCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#validateJoinCode, [code]),
            returnValue: _i3.Future<_i4.Event?>.value(),
          )
          as _i3.Future<_i4.Event?>);

  @override
  _i3.Future<void> assertUploadLimit(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#assertUploadLimit, [eventId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> executeOfflineUpload(String? eventId, _i5.File? photoFile) =>
      (super.noSuchMethod(
            Invocation.method(#executeOfflineUpload, [eventId, photoFile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
